github_repository = "hawkab/ubuntu-dock-folders"
apt_repository = "hawkab/apt"
apt_branch = "main"
apt_url = "https://hawkab.github.io/apt/"
launchpad_owner = "hwakaba"
launchpad_archive = "ubuntu-dock-folders"
suite = "noble"
architecture = "amd64"
signing_fingerprint = "D4FE96494637320FCA25DD35E94D1A6D97CE2319"
launchpad_transport = "ftp"
